# Generated by Django 5.2 on 2025-10-30 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échec'), ('refunded', 'Remboursé'), ('waiting_payment', 'En attente de paiement'), ('payment_verified', 'Paiement vérifié')], default='pending', max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('tax_amount', models.PositiveIntegerField(default=0)),
                ('final_amount', models.PositiveIntegerField(default=0)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('om', 'Orange Money'), ('momo', 'MTN Mobile Money')], max_length=20)),
                ('payment_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/')),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('cart_items', models.JSONField(default=list)),
                ('shop_id', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('ussd_code', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='payments.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
