# Generated by Django 5.2 on 2025-11-10 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_paymentverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodpaid',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodpaid',
            name='payment_method',
            field=models.CharField(choices=[('om', 'Orange Money'), ('momo', 'MTN Mobile Money')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
