# Generated by Django 5.2 on 2025-12-07 18:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre du témoignage')),
                ('content', models.TextField(max_length=1000, verbose_name='Contenu du témoignage')),
                ('author_name', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('author_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle/Profession')),
                ('author_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entreprise/Organisation')),
                ('author_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation')),
                ('category', models.CharField(choices=[('customer', 'Client'), ('partner', 'Partenaire'), ('farmer', 'Agriculteur'), ('expert', 'Expert'), ('general', 'Général')], default='customer', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('published', 'Publié'), ('archived', 'Archivé')], default='pending', max_length=20, verbose_name='Statut')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/authors/', verbose_name="Photo de l'auteur")),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='testimonials/featured/', verbose_name='Image mise en avant')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('allow_display', models.BooleanField(default=True, verbose_name="Autoriser l'affichage public")),
                ('is_verified', models.BooleanField(default=False, verbose_name="Vérifié par l'équipe")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Contenu')),
                ('comment_type', models.CharField(choices=[('article', 'Commentaire Article'), ('testimonial', 'Commentaire Témoignage')], default='article', max_length=20, verbose_name='Type de commentaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('spam', 'Spam')], default='pending', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('moderation_reason', models.TextField(blank=True, null=True, verbose_name='Raison de la modération')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.article', verbose_name='Article')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contacts.comment', verbose_name='Commentaire parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contacts.testimonial', verbose_name='Témoignage')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contacts.comment', verbose_name='Commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like de commentaire',
                'verbose_name_plural': 'Likes de commentaires',
                'indexes': [models.Index(fields=['comment', 'user'], name='contacts_co_comment_73a085_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam ou publicité'), ('offensive', 'Contenu offensant'), ('inappropriate', 'Contenu inapproprié'), ('fake', 'Information fausse'), ('other', 'Autre')], max_length=20, verbose_name='Raison du signalement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description supplémentaire')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Signalement traité')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notes de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contacts.comment', verbose_name='Commentaire signalé')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalant')),
            ],
            options={
                'verbose_name': 'Signalement de commentaire',
                'verbose_name_plural': 'Signalements de commentaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment', 'is_resolved'], name='contacts_co_comment_16779e_idx'), models.Index(fields=['created_at'], name='contacts_co_created_5f237c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status'], name='contacts_te_status_4ce6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['category'], name='contacts_te_categor_504d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['rating'], name='contacts_te_rating_c58a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_featured'], name='contacts_te_is_feat_f8c02a_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['published_at'], name='contacts_te_publish_8c44f6_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status'], name='contacts_co_status_dbe58a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='contacts_co_created_5181ac_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='contacts_co_user_id_6d3b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status'], name='contacts_co_article_681d02_idx'),
        ),
    ]
