# Generated by Django 5.2 on 2025-12-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('a sdmin', 'Admin'), ('seller', 'Agriculteur/Vendeur'), ('client', 'Client/Utilisateur')], max_length=10),
        ),
    ]
