# Generated by Django 5.2 on 2025-12-07 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('unsubscribed', 'Désabonné')], default='active', max_length=20, verbose_name='Statut')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de désabonnement')),
                ('source', models.CharField(default='blog', help_text="Page où l'utilisateur s'est inscrit", max_length=100, verbose_name="Source d'inscription")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, verbose_name='Token de confirmation')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Email confirmé')),
                ('last_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='Dernier email envoyé')),
                ('preferences', models.JSONField(default=dict, help_text="Préférences de l'utilisateur", verbose_name='Préférences')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonné à la newsletter',
                'verbose_name_plural': 'Abonnés à la newsletter',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='client_news_email_7abb73_idx'), models.Index(fields=['status'], name='client_news_status_85054d_idx'), models.Index(fields=['subscribed_at'], name='client_news_subscri_ad9717_idx')],
            },
        ),
    ]
