# Generated by Django 5.2 on 2025-10-20 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_alter_category_id_shop_category_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='note',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='type_shop',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
