# Generated by Django 5.2 on 2025-10-20 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0003_shop_note_shop_type_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='localisation',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
