# Generated by Django 5.2 on 2025-10-20 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0004_shop_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(to='Marketplace.Shop', on_delete=models.CASCADE, null=True, blank=True),
            preserve_default=False,
        ),
    ]
