# Generated by Django 5.2 on 2025-10-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Marketplace', '0008_productview_searchhistory_productlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_contenu', models.CharField(choices=[('article', 'Article (texte)'), ('affiche', 'Affiche (image)'), ('podcast', 'Podcast (vidéo)')], default='article', max_length=20)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, help_text='Boutique qui a publié cet article', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='Marketplace.shop')),
            ],
        ),
    ]
