# Generated by Django 5.2 on 2025-11-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Boutique qui a publié cet article', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='Marketplace.shop'),
        ),
    ]
